#!/bin/bash

if [[ ! "$1" ]]; then
  echo "No task selected!"
  exit 1
fi

x=task_$(printf "%03d\n" "$1")

if [[ -d $x ]]; then
  echo "This task already exists!"
  exit 1
fi

echo Downloading Task $x
cookie="$(cat cookie)"

mkdir $x
curl "https://scoreboard.sec.in.tum.de/tasks/$1/dl" -o task.zip -b "$cookie"
unzip task.zip -d $x
rm task.zip

html=$(curl "https://scoreboard.sec.in.tum.de/tasks/$1" -b "$cookie")
url=$(echo "$html" | grep -Eo 'href="(.*)">\1' | grep -Eo '[^>]*$')
pw=$(echo "$html" | grep -Eo "Passwor[dt]: [0-9a-f]*?" | cut -d " " -f 2)
cat <<EOF > $x/header.txt
import re
flag = lambda x: print(re.findall(r'flag\{.*?\}', x)[0])
URL = "$url"
PASSWORD = "$pw"
EOF
