#!/bin/bash

x=$(basename $PWD | cut -d"_" -f2 | bc)

if [[ ! "$1" ]]; then
  if [[ -f "pwn-students.py" ]]; then
    file="pwn-students.py"
  else
    file="pwn_students.py"
  fi
else
  file="$1"
fi

cookie="$(cat ../cookie)"
curl -X POST "https://netsec.net.in.tum.de/tasks/$x/upload" -b "$cookie" -F fileupload=@"$file"
